version: '3'
services:
  jenkins:
    build: .
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
      - "5001:5001"
    volumes:
      - ./jenkins_data:/var/jenkins_home
